blank_issues_enabled: false
contact_links:
  - name: Want to ask questions about NasUX or NasTech AI?
    url: https://github.com/nastech-ai/NasTech-Agent/discussions
    about: Join GitHub Discussions
  - name: NasTech AI Agent issues
    url: https://github.com/nastech-ai/NasTech-Agent/issues
    about: Report issues with the NasTech AI Agent
