name: Trigger NasUX Library Builds on Jitpack

on:
  release:
    types:
      - published

jobs:
  trigger-nasux-library-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Set vars
        run: echo "NASUX_LIB_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Echo release
        run: echo "Triggering NasUX library builds on jitpack for '$NASUX_LIB_VERSION' release after waiting for 3 mins"
      - name: Trigger NasUX library builds on jitpack
        run: |
          sleep 180
          curl --max-time 600 --no-progress-meter "https://jitpack.io/com/nastech/nasux-app/terminal-emulator/$NASUX_LIB_VERSION/terminal-emulator-$NASUX_LIB_VERSION.pom"
          curl --max-time 600 --no-progress-meter "https://jitpack.io/com/nastech/nasux-app/terminal-view/$NASUX_LIB_VERSION/terminal-view-$NASUX_LIB_VERSION.pom"
          curl --max-time 600 --no-progress-meter "https://jitpack.io/com/nastech/nasux-app/nasux-shared/$NASUX_LIB_VERSION/nasux-shared-$NASUX_LIB_VERSION.pom"
